services:
  api:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./yii2-rest-api:/var/www/html
    depends_on:
      - db
    networks:
      - api-net

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: yii2db
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2pass
    ports:
      - "3306:3306"
    networks:
      - api-net
    volumes:
      - api-db-data:/var/lib/mysql

networks:
  api-net:

volumes:
  api-db-data:
